# Generated by Django 6.0.6 on 2026-07-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="E.g., 'bear' or '240809'", max_length=200)),
                ('slug', models.SlugField(help_text="E.g., '230919-bear' or '240809'", unique=True)),
                ('content_markdown', models.TextField(help_text='Raw Markdown content.')),
                ('publish_date', models.DateTimeField(help_text='Publish date of the entry.')),
                ('share_to_bluesky', models.BooleanField(default=False, help_text='Post this entry to Bluesky upon saving.')),
                ('share_to_mastodon', models.BooleanField(default=False, help_text='Post this entry to Mastodon upon saving.')),
                ('posted_to_bluesky', models.BooleanField(default=False)),
                ('posted_to_mastodon', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL (e.g. 'words', 'sounds').", unique=True)),
                ('content_markdown', models.TextField(help_text='Raw Markdown content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='log_assets/')),
                ('custom_filename', models.CharField(blank=True, help_text="Optional: Rename file (e.g. 'glow.mp4'). Leave blank to auto-rename based on log slug.", max_length=100)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.logentry')),
            ],
        ),
    ]
