# Generated by Django 6.0.6 on 2026-07-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_gbg_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='page_assets/')),
                ('custom_filename', models.CharField(blank=True, help_text="Optional: Rename file (e.g. 'performance.jpg'). Leave blank to auto-rename based on page slug.", max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.page')),
            ],
        ),
    ]
